spring:
  application:
    name: server
  datasource:
    driver-class-name: org.h2.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100

logging:
  level:
    com.lovememoir.server: debug
    org.hibernate.SQL: debug
