spring:
  application:
    name: server
  datasource:
    driver-class-name: org.h2.Driver
#    url: ${datasource.url}  # IntelliJ 데이터소스 사용법 체크
#    username: ${datasource.username}
#    password: ${datasource.password}
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100

logging:
  level:
    com.lovememoir.server: debug
    org.hibernate.SQL: debug
