spring:
  application:
    name: server
  datasource:
    driver-class-name: org.h2.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  ai:
    openai:
      api-key: ${openai.api-key}
      chat:
        options:
          model: gpt-4
          temperature: 0.7
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            client-authentication-method: client_secret_post
            authorization-grant-type: credentials
            scope:
              - profile_nickname
              - profile_image
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Kakao
          apple:
            client-id: ${apple.client-id}
            client-secret: ${apple.client-secret}
            client-authentication-method: client_secret_post
            authorization-grant-type: credentials
            scope:
              - name
              - email
            client-name: Apple
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          google:
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
  data:
    redis:
      host: ${redis.url}
      port: ${redis.port}

app:
  auth:
    token:
      tokenSecret: ${auth.token.tokenSecret}
      tokenExpiry: ${auth.token.tokenExpiry}

logging:
  level:
    com.lovememoir.server: debug
    org.hibernate.SQL: debug

cloud:
  aws:
    credentials:
      accessKey: ${s3.accessKey}
      secretKey: ${s3.secretKey}
    s3:
      bucket: love-memoir
    stack:
      auto: false
    region:
      static: ap-northeast-2